// Generated by typings
// Source: typings/arachne-components.d.ts
declare module 'arachne-components' {
	import * as React from 'react';
	import { Reducer } from 'redux';

	module 'arachne-components' {
		class Avatar extends React.Component<any, any> {}
		class BadgedIcon extends React.Component<any, any> {}
		class Button extends React.Component<any, any> {}
		class FacetedSearchPanel extends React.Component<any, any> {}
		class Form extends React.Component<any, any> {}
		class FormInput extends React.Component<any, any> {}
		class FormSelect extends React.Component<any, any> {}
		class Header extends React.Component<any, any> {}
		class Link extends React.Component<any, any> {}
		class ListItem extends React.Component<any, any> {}
		class LoadingPanel extends React.Component<any, any> {}
		class Panel extends React.Component<any, any> {}
		class PageContent extends React.Component<any, any> {}
		class Pagination extends React.Component<any, any> {}
		class Select extends React.Component<any, any> {}
		class Table extends React.Component<any, any> {}
		class TableCellLink extends React.Component<any, any> {}
		class TableCellText extends React.Component<any, any> {}
		class Checkbox extends React.Component<any, any> {}
		class Modal extends React.Component<any, any> {}
		class Toolbar extends React.Component<any, any> {}
		class Tabs extends React.Component<any, any> {}
		class FormAutocomplete extends React.Component<any, any> {}
		class FormCheckboxList extends React.Component<any, any> {}
		class FormCheckboxListFilterable extends React.Component<any, any> {}
		class RadioButton extends React.Component<any, any> {}
		class TabbedPane extends React.Component<any, any> {}
		module ModalUtils {			
			const connect: Function;
			const actions: {
				toggle: Function;
			};
			const reducer: Reducer<any>;
		}
	}
}
