// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/f676f726ee69ef6f06c355540280f34fa3b9ed4e/redux-promise-middleware/index.d.ts
declare module 'redux-promise-middleware' {
// Type definitions for redux-promise-middleware
// Project: https://github.com/pburtchaell/redux-promise-middleware
// Definitions by: ianks <https://github.com/ianks>
// Definitions: https://github.com/borisyankov/DefinitelyTyped

import { Middleware } from 'redux';

export default function promiseMiddleware(config?: { promiseTypeSuffixes: string[] }): Middleware;
}
